name: CI
on:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala-version: [ 2.13.7 ]
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 100
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
      - name: gradle test ${{ github.ref }}
        run: ./gradlew check
        env:
          SCALA_VERSION: ${{ matrix.scala-version }}
